version: '3'

services:
  backend:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    image: "viktormilosavljevic/test-assignment/backend"
    ports:
      - "5000:5000"
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: "viktormilosavljevic/test-assignment/frontend"
    ports:
      - "3000:3000"
    links:
      - backend